#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the defcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 *
 * Updated: 2026-01-11 from DNS seeds
 */
static SeedSpec6 pnSeed6_main[] = {
    // Active nodes - Updated 2026-01-16
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x49,0x34,0xb6,0xcc}, 1337}, // 73.52.182.204
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x42,0x2a,0x5b,0xe1}, 1337}, // 66.42.91.225
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
